language: java
sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.embedpostgresql

dist: trusty64
group: stable
jdk: oraclejdk10


before_install:
  - chmod +x mvnw

  before_script:
    -adduser contactfilter
